version: '3.8'

services:
  # Redis (pode usar Redis Cloud ou Upstash)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - atendeai-network

  # Backend API
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    networks:
      - atendeai-network
    restart: unless-stopped

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - atendeai-network
    restart: unless-stopped

networks:
  atendeai-network:
    driver: bridge 