[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "cd backend && python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd backend && python migrate_db.py && python init_db.py && python -m uvicorn main:app --host 0.0.0.0 --port $PORT" 