[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python migrate_db.py && python init_db.py && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 